services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
      - DATABASE_NAME=digitana
      - DATABASE_USER=digitana
      - DATABASE_PASSWORD=digitana
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=digitana
      - POSTGRES_USER=digitana
      - POSTGRES_PASSWORD=digitana

volumes:
  postgres_data:
