# Generated by Django 5.2.9 on 2025-12-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infomaniak_client_id', models.CharField(blank=True, help_text='Infomaniak OAuth2 Client ID', max_length=255)),
                ('infomaniak_client_secret', models.CharField(blank=True, help_text='Infomaniak OAuth2 Client Secret', max_length=255)),
            ],
        ),
    ]
