# Generated by Django 5.2.9 on 2025-12-04 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('storage', 'Storage'), ('calendar', 'Calendar'), ('newsletter', 'Newsletter'), ('media', 'Media'), ('other', 'Other')], default='other', max_length=20)),
                ('base_url', models.URLField(help_text='Base URL of the service API.')),
                ('auth_method', models.CharField(choices=[('oauth2', 'OAuth2'), ('api_key', 'API Key'), ('basic', 'Basic Auth')], default='oauth2', max_length=20)),
                ('required_scopes', models.JSONField(blank=True, default=list, help_text='List of required scopes for this service.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Specific configuration (e.g., folder IDs, calendar IDs).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(help_text='The circle that owns/uses this integration instance.', on_delete=django.db.models.deletion.CASCADE, related_name='integration_instances', to='core.circle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='integrations.integrationservice')),
            ],
        ),
        migrations.CreateModel(
            name='UserIntegrationIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(help_text='ID of the user in the external system.', max_length=255)),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted credentials (tokens, refresh tokens). SECURITY WARNING: Ensure this is handled securely.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identities', to='integrations.integrationservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User integration identities',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
