# Generated by Django 5.2.9 on 2025-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationservice',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Provider credentials (client_id, client_secret).'),
        ),
    ]
